import numpy as np

plateau = "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRREEEREREEERERSREREREEEREREEHHERRRRERRRERRRRRHRRRRRHRRRERRRRRERRERERHEEREREHERHRERERHRERSRHHHRRRRRRERERRRRRERRRRRRRERERRRRRHRRSRHREREEHEEREHERERERHREESRSRERRRRERSRRRERRRRRERERHRERRRERERRRRERHREREREEERHRHREREREREREEERERRERRRRREREEERERRRERERRRRRRRERERRHREREREREEESHEHREEEEERERERERERRRRRRERRREEERRRRRRRHEERRRRRRRRRRHRERHRHRHEEEEREEEEEEHREREHESERRRRHRERHREEERRRRRRRERHRRRSRRRERRESERHEEREEHEEEERERERERHRHRSHERRRREREEERRRRRRRERERRRRRERERERRRREREEEEHREREHERERHEEREREEEREHERRRRRRERRRRRERERRRHRRRERRRRRRRERREEHEEESRHREREREEEREHHRERESERERRERSEERRRRRRRERRRRRHRRRERRRERSRREREEERERERHRERHSERERHEEREHERERRRRHRERERRRRRRRRRERERERRRRRRRERRERERERHESREEEEERERERHREEEREHERRRRRRERRRRRERRRRRRRRRRRERRRRRRRREHEEEREEEREREHEREHHRSREREREEERREEEEERRRRRERRREREEERERERRRERRRRESSEERERHREEEEERHEERHREHEEEEERRRRRRRRRRERRRRRERHEERRRERERERRRRHRERSHHRERERERHEEEEHESSRERERERRERERRRRRHRRRRRRRRRHRRRRRRRERRRREEERERERHEESESHREEEEEHERERERERRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"

plateau = ','.join(plateau[i:i+31] for i in range(0, len(plateau), 6))

print(plateau)

tab = plateau.split(',')

print(tab)

arr = ['']

for string in tab:
    print(string)
    string = ','.join(string[i:i+1] for i in range(0, len(plateau)))
    arr.append(string.split(','))
    
print(arr)
    
